name: Publish Docker image

on:
  push:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.Dusername}}
          password: ${{secrets.Dpassword}}
      
      - name: Build Docker Image
        run: docker build -t stories .
        
      - name: Tag Docker Image
        run: docker tag devops:latest ${{secrets.Dusername}}/hm:latest
      
      - name: Push Docker Image
        run: docker push ${{secrets.Dusername}}/hm:latest
